import type { GlossaryTerm } from "@/lib/glossary/types"

export const CHARTS: GlossaryTerm[] = [
  {
    slug: "candlestick",
    term: "Candlestick",
    aliases: ["candle", "Japanese candlestick", "body", "bullish candle", "bearish candle"],
    category: "charts",
    level: "beginner",
    short: "A chart bar showing the open, high, low and close of a period, with a coloured body between open and close.",
    detail: ["Green (bullish) candles closed above their open; red (bearish) ones closed below. Candlesticks trace back to Japanese rice traders in the 1700s."],
    visual: "candle",
    related: ["ohlc", "wick", "timeframe"],
    lessonId: "u3-anatomy-of-a-candle",
  },
  {
    slug: "ohlc",
    term: "OHLC",
    aliases: ["open high low close", "bar chart", "line chart"],
    category: "charts",
    level: "beginner",
    short: "Open, high, low and close: the four prices every bar or candle summarises.",
    detail: ["Line charts show only closes; bar and candle charts show all four."],
    related: ["candlestick", "timeframe"],
    lessonId: "u3-line-bar-and-candle-charts",
  },
  {
    slug: "wick",
    term: "Wick",
    aliases: ["shadow", "tail", "long wick", "long upper wick", "long lower wick"],
    category: "charts",
    level: "beginner",
    short: "The thin line above or below a candle's body, reaching to its high or low.",
    detail: ["Long wicks show prices that were visited and rejected within the candle. In SMC, a wick beyond a level that closes back inside is often a liquidity sweep."],
    visual: "candle",
    related: ["candlestick", "liquidity-sweep", "rejection-block"],
    lessonId: "u3-anatomy-of-a-candle",
  },
  {
    slug: "timeframe",
    term: "Timeframe",
    aliases: ["TF", "HTF", "LTF", "higher timeframe", "lower timeframe"],
    category: "charts",
    level: "beginner",
    short: "How much time each candle covers: 1 minute, 15 minutes, 1 hour, 1 day and so on.",
    detail: ["Higher timeframes (HTF) move slower and carry more weight; lower timeframes (LTF) show detail for timing entries."],
    example: "One 1-hour candle contains twelve 5-minute candles.",
    related: ["multi-timeframe-analysis", "candlestick"],
    lessonId: "u3-timeframes",
  },
  {
    slug: "volume",
    term: "Volume",
    category: "charts",
    level: "beginner",
    short: "How much of an asset traded during each candle.",
    detail: ["Rising volume behind a move suggests conviction. Spot forex shows broker tick volume, not total market volume."],
    visual: "volume",
    related: ["tick-volume", "vwap", "volume-profile"],
    lessonId: "u3-volume",
  },
  {
    slug: "tick-volume",
    term: "Tick volume",
    category: "charts",
    level: "intermediate",
    short: "The number of price changes in a candle, used as a stand-in for volume in spot forex.",
    detail: ["It reflects your broker's feed only. Currency futures on CME show real exchange volume."],
    related: ["volume", "forex"],
    lessonId: "u3-volume",
  },
  {
    slug: "doji",
    term: "Doji",
    category: "charts",
    level: "beginner",
    short: "A candle whose open and close are almost equal: buyers and sellers fought to a draw.",
    detail: ["After a strong move, a doji can be an early sign the move is losing steam. On its own it predicts little."],
    visual: "doji",
    related: ["spinning-top", "candlestick"],
    lessonId: "u3-single-candle-patterns",
  },
  {
    slug: "spinning-top",
    term: "Spinning top",
    category: "charts",
    level: "beginner",
    short: "A small-bodied candle with wicks on both sides, showing indecision.",
    detail: [],
    related: ["doji", "candlestick"],
    lessonId: "u3-single-candle-patterns",
  },
  {
    slug: "hammer",
    term: "Hammer",
    aliases: ["pin bar"],
    category: "charts",
    level: "beginner",
    short: "A small body near the top with a long lower wick, after a decline: lower prices were rejected.",
    detail: ["The lower wick should be at least twice the body. It matters most at a support level or after a liquidity sweep."],
    visual: "hammer",
    related: ["shooting-star", "rejection-block", "support"],
    lessonId: "u3-single-candle-patterns",
  },
  {
    slug: "shooting-star",
    term: "Shooting star",
    category: "charts",
    level: "beginner",
    short: "A small body near the bottom with a long upper wick, after a rally: higher prices were rejected.",
    detail: [],
    related: ["hammer", "resistance"],
    lessonId: "u3-single-candle-patterns",
  },
  {
    slug: "marubozu",
    term: "Marubozu",
    category: "charts",
    level: "intermediate",
    short: "A big-bodied candle with little or no wick: one side controlled the whole period.",
    detail: [],
    related: ["displacement", "candlestick"],
    lessonId: "u3-single-candle-patterns",
  },
  {
    slug: "engulfing",
    term: "Engulfing pattern",
    aliases: ["bullish engulfing", "bearish engulfing"],
    category: "charts",
    level: "beginner",
    short: "A candle whose body completely covers the previous candle's opposite-coloured body.",
    detail: ["A bullish engulfing after a decline shows buyers overwhelming sellers in one period; a bearish engulfing after a rally is the mirror."],
    visual: "engulfing",
    related: ["hammer", "inside-bar"],
    lessonId: "u3-two-and-three-candle-patterns",
  },
  {
    slug: "inside-bar",
    term: "Inside bar",
    category: "charts",
    level: "intermediate",
    short: "A candle whose whole range sits inside the previous candle's range: a pause before a possible breakout.",
    detail: [],
    related: ["engulfing", "breakout"],
    lessonId: "u3-two-and-three-candle-patterns",
  },
  {
    slug: "morning-star",
    term: "Morning star",
    aliases: ["evening star"],
    category: "charts",
    level: "intermediate",
    short: "A three-candle bottoming pattern: a strong red candle, a small pause candle, then a strong green one. Evening star is the bearish mirror.",
    detail: [],
    related: ["engulfing", "doji"],
    lessonId: "u3-two-and-three-candle-patterns",
  },
  {
    slug: "gap",
    term: "Gap",
    aliases: ["gap up", "gap down", "gap fill", "common gap", "breakaway gap", "runaway gap", "exhaustion gap"],
    category: "charts",
    level: "beginner",
    short: "Empty space on a chart where price opened away from the previous close and nothing traded in between.",
    detail: ["Stocks gap often on overnight news and earnings; futures and forex mostly over weekends. Gaps often fill, but not always. Not to be confused with a fair value gap."],
    visual: "gap",
    related: ["fair-value-gap", "earnings", "ndog-nwog"],
    lessonId: "u3-gaps",
  },
  {
    slug: "log-scale",
    term: "Log scale",
    aliases: ["logarithmic scale", "linear scale", "linear", "logarithmic"],
    category: "charts",
    level: "intermediate",
    short: "A chart scale where equal heights mean equal percentage moves, not equal price amounts.",
    detail: ["Use it for long-term charts and assets with big percentage moves, like Bitcoin over years."],
    related: ["timeframe"],
    lessonId: "u3-log-vs-linear-scale",
  },
]
