import type { GlossaryTerm } from "@/lib/glossary/types"

export const INDICATORS: GlossaryTerm[] = [
  {
    slug: "indicator",
    term: "Indicator",
    aliases: ["lagging indicator", "technical indicator", "lag"],
    category: "indicators",
    level: "beginner",
    short: "A formula applied to past prices or volume; it describes what price did and always lags.",
    detail: ["Faster settings lag less but give more false signals. Use indicators to describe conditions and confirm structure, not to predict."],
    related: ["moving-average", "rsi", "confluence"],
    lessonId: "u6-why-indicators-lag",
  },
  {
    slug: "moving-average",
    term: "Moving average",
    aliases: ["MA", "SMA", "EMA", "200 MA", "trend filter"],
    category: "indicators",
    level: "beginner",
    short: "The average closing price of the last N candles, recalculated each candle to smooth out noise.",
    detail: ["An SMA weights every candle equally; an EMA favours recent candles and reacts faster. Uses: trend filter, dynamic support, crossovers."],
    example: "Closes 10, 12, 14, 16, 18: the 5-period SMA is 14.",
    visual: "moving-average",
    related: ["golden-cross", "indicator", "vwap"],
    lessonId: "u6-moving-averages",
  },
  {
    slug: "golden-cross",
    term: "Golden cross",
    aliases: ["death cross", "crossover"],
    category: "indicators",
    level: "beginner",
    short: "The 50-day moving average crossing above the 200-day; the death cross is the cross below.",
    detail: ["Crossovers work in trends and whipsaw in ranges."],
    related: ["moving-average"],
    lessonId: "u6-moving-averages",
  },
  {
    slug: "rsi",
    term: "RSI",
    aliases: ["relative strength index"],
    category: "indicators",
    level: "beginner",
    short: "Wilder's momentum oscillator from 0 to 100 comparing recent gains with recent losses.",
    detail: ["RSI = 100 − 100 ÷ (1 + average gain ÷ average loss), usually over 14 candles. Above 70 is overbought and below 30 oversold, but strong trends can stay there."],
    example: "Average gain 2, average loss 1: RS = 2, RSI = 66.7.",
    visual: "rsi",
    related: ["overbought-oversold", "divergence", "macd"],
    lessonId: "u6-rsi",
  },
  {
    slug: "overbought-oversold",
    term: "Overbought and oversold",
    aliases: ["overbought", "oversold"],
    category: "indicators",
    level: "beginner",
    short: "Oscillator readings at an extreme (RSI above 70 or below 30); they describe strength, not a turning point.",
    detail: [],
    related: ["rsi", "stochastic"],
    lessonId: "u6-rsi",
  },
  {
    slug: "stochastic",
    term: "Stochastic",
    aliases: ["stoch", "stochastic oscillator"],
    category: "indicators",
    level: "intermediate",
    short: "A momentum oscillator comparing the close with the recent high-low range.",
    detail: ["It measures much the same thing as RSI, so using both adds little."],
    related: ["rsi", "overbought-oversold"],
    lessonId: "u6-divergence-and-combining-tools",
  },
  {
    slug: "macd",
    term: "MACD",
    aliases: ["moving average convergence divergence", "histogram", "MACD line", "signal line"],
    category: "indicators",
    level: "intermediate",
    short: "The gap between a 12 and a 26-period EMA, with a 9-period signal line and a histogram.",
    detail: ["Above zero means upward momentum. Crossovers show momentum turning; a shrinking histogram warns earlier."],
    visual: "macd",
    related: ["moving-average", "rsi", "divergence"],
    lessonId: "u6-macd",
  },
  {
    slug: "bollinger-bands",
    term: "Bollinger Bands",
    aliases: ["BB", "squeeze"],
    category: "indicators",
    level: "intermediate",
    short: "A 20-period SMA with bands two standard deviations above and below; narrow bands (a squeeze) often precede big moves.",
    detail: ["Price can walk a band in a strong trend, so touches aren't automatic signals."],
    example: "SMA 100 and standard deviation 1.5: the upper band is 103.",
    visual: "bollinger",
    related: ["atr", "moving-average"],
    lessonId: "u6-bollinger-bands",
  },
  {
    slug: "atr",
    term: "ATR",
    aliases: ["average true range", "true range", "volatility measure"],
    category: "indicators",
    level: "intermediate",
    short: "Wilder's measure of volatility: how far price typically moves per candle, including gaps. No direction.",
    detail: ["Many traders place stops 1.5 to 2 ATR away so normal noise doesn't hit them."],
    example: "Long at 5,000 with ATR 6 and a 2 ATR stop: stop at 4,988.",
    visual: "atr",
    related: ["stop-loss", "bollinger-bands", "position-sizing"],
    lessonId: "u6-atr",
  },
  {
    slug: "vwap",
    term: "VWAP",
    aliases: ["volume-weighted average price", "anchored VWAP"],
    category: "indicators",
    level: "intermediate",
    short: "The volume-weighted average price of the session; above it leans bullish, below it bearish.",
    detail: ["VWAP resets each session. Anchored VWAP starts from a candle you choose, such as a big swing low."],
    example: "100 shares at $10 and 300 at $12: VWAP = $11.50.",
    related: ["volume", "volume-profile", "moving-average"],
    lessonId: "u6-vwap-and-volume-tools",
  },
  {
    slug: "volume-profile",
    term: "Volume profile",
    aliases: ["POC", "point of control", "value area"],
    category: "indicators",
    level: "advanced",
    short: "Volume shown by price instead of by time; the busiest price is the point of control (POC).",
    detail: ["High-volume prices act like magnets; low-volume prices are crossed quickly."],
    related: ["vwap", "volume", "liquidity-void"],
    lessonId: "u6-vwap-and-volume-tools",
  },
  {
    slug: "divergence",
    term: "Divergence",
    aliases: ["bearish divergence", "bullish divergence", "hidden divergence"],
    category: "indicators",
    level: "intermediate",
    short: "Price and an oscillator disagreeing: a higher high in price with a lower high in RSI, for example.",
    detail: ["It warns that momentum is fading but doesn't time the turn. Wait for structure to confirm."],
    visual: "divergence",
    related: ["rsi", "macd", "smt-divergence"],
    lessonId: "u6-divergence-and-combining-tools",
  },
  {
    slug: "confluence",
    term: "Confluence",
    category: "indicators",
    level: "intermediate",
    short: "Several independent reasons pointing to the same price and direction; it raises the odds, never to certainty.",
    detail: ["Combine tools that measure different things (structure, a level, momentum, time) rather than several of the same kind."],
    related: ["point-of-interest", "indicator", "unicorn"],
    lessonId: "u6-divergence-and-combining-tools",
  },
  {
    slug: "volatility",
    term: "Volatility",
    category: "indicators",
    level: "beginner",
    short: "How much and how fast price moves; high volatility means bigger swings in both directions.",
    detail: ["ATR and Bollinger Band width measure it. Higher volatility calls for wider stops and smaller position size."],
    related: ["atr", "bollinger-bands", "position-sizing"],
    lessonId: "u6-atr",
  },
  {
    slug: "momentum",
    term: "Momentum",
    category: "indicators",
    level: "beginner",
    short: "The speed and strength of a price move; oscillators like RSI and MACD measure it.",
    detail: [],
    related: ["rsi", "macd", "divergence"],
    lessonId: "u6-rsi",
  },
]
