import type { GlossaryTerm } from "@/lib/glossary/types"

export const LEVELS: GlossaryTerm[] = [
  {
    slug: "support",
    term: "Support",
    category: "levels",
    level: "beginner",
    short: "A price area where falling prices have stopped before, because buyers stepped in.",
    detail: ["Draw it as a zone, not a thin line. Each test uses up buy orders, and obvious levels collect stops just beyond them."],
    visual: "support",
    related: ["resistance", "role-reversal", "demand-zone"],
    lessonId: "u5-support-and-resistance",
  },
  {
    slug: "resistance",
    term: "Resistance",
    category: "levels",
    level: "beginner",
    short: "A price area where rising prices have stopped before, because sellers stepped in.",
    detail: [],
    related: ["support", "role-reversal", "demand-zone"],
    lessonId: "u5-support-and-resistance",
  },
  {
    slug: "role-reversal",
    term: "Role reversal",
    aliases: ["flip", "S/R flip", "polarity"],
    category: "levels",
    level: "intermediate",
    short: "Broken resistance becoming support (or broken support becoming resistance).",
    detail: ["Trapped traders and late buyers act at the old level, which is why retests often hold."],
    related: ["retest", "support", "resistance"],
    lessonId: "u5-role-reversal",
  },
  {
    slug: "round-number",
    term: "Round number",
    aliases: ["psychological level", "big figure"],
    category: "levels",
    level: "beginner",
    short: "Prices like 1.1000 or 100,000 where orders cluster, so they act like support and resistance.",
    detail: ["Price often turns just before them or runs just beyond them. Avoid hiding your stop right next to one."],
    related: ["support", "stop-hunt"],
    lessonId: "u5-round-numbers",
  },
  {
    slug: "trendline",
    term: "Trendline",
    aliases: ["channel"],
    category: "levels",
    level: "beginner",
    short: "A line joining swing lows in an uptrend (or highs in a downtrend); a parallel line makes a channel.",
    detail: ["A third touch confirms it. A trendline break is a warning, not a reversal; structure confirms."],
    visual: "trendline",
    related: ["support", "trendline-liquidity"],
    lessonId: "u5-trendlines-and-channels",
  },
  {
    slug: "demand-zone",
    term: "Demand zone",
    aliases: ["supply zone", "supply and demand", "base"],
    category: "levels",
    level: "intermediate",
    short: "The base price left in a hurry before a strong rally (a supply zone is the base before a strong drop).",
    detail: ["Fresh zones that haven't been revisited are considered strongest. Order blocks are a sharper version of the same idea."],
    related: ["order-block", "support"],
    lessonId: "u5-supply-and-demand-zones",
  },
  {
    slug: "double-top",
    term: "Double top",
    aliases: ["double bottom"],
    category: "levels",
    level: "beginner",
    short: "Two failed attempts at the same high, completed by a close below the low between them (the neckline).",
    detail: ["To an SMC trader, the twin highs are also buy-side liquidity that may get swept first."],
    visual: "double-top",
    related: ["head-and-shoulders", "equal-highs-lows", "measured-move"],
    lessonId: "u5-classic-reversal-patterns",
  },
  {
    slug: "head-and-shoulders",
    term: "Head and shoulders",
    aliases: ["inverse head and shoulders", "H&S", "neckline"],
    category: "levels",
    level: "intermediate",
    short: "Three peaks with the middle one highest; a close through the neckline completes the reversal.",
    detail: ["The lower right shoulder shows buyers weakening: a lower high."],
    visual: "head-and-shoulders",
    related: ["double-top", "measured-move", "change-of-character"],
    lessonId: "u5-classic-reversal-patterns",
  },
  {
    slug: "measured-move",
    term: "Measured move",
    category: "levels",
    level: "intermediate",
    short: "A rough target that projects a pattern's height from its breakout point.",
    detail: [],
    example: "Head at 105.5, neckline at 101.8: height 3.7, target 101.8 − 3.7 = 98.1.",
    related: ["head-and-shoulders", "fibonacci-extension"],
    lessonId: "u5-classic-reversal-patterns",
  },
  {
    slug: "flag",
    term: "Flag",
    aliases: ["bull flag", "bear flag", "pennant"],
    category: "levels",
    level: "intermediate",
    short: "A small channel sloping against a sharp move (the pole), usually followed by continuation.",
    detail: ["A pennant is the same idea with a small converging triangle."],
    related: ["triangle", "wedge", "breakout"],
    lessonId: "u5-continuation-patterns",
  },
  {
    slug: "triangle",
    term: "Triangle",
    aliases: ["ascending triangle", "descending triangle", "symmetrical triangle", "continuation pattern"],
    category: "levels",
    level: "intermediate",
    short: "Price squeezing between two converging lines until it breaks out.",
    detail: ["Ascending (flat highs, rising lows) leans up; descending leans down; symmetrical can go either way."],
    related: ["flag", "wedge", "breakout"],
    lessonId: "u5-continuation-patterns",
  },
  {
    slug: "wedge",
    term: "Wedge",
    aliases: ["rising wedge", "falling wedge"],
    category: "levels",
    level: "intermediate",
    short: "Two converging lines sloping the same way; rising wedges often break down, falling wedges often break up.",
    detail: [],
    related: ["triangle", "flag"],
    lessonId: "u5-continuation-patterns",
  },
  {
    slug: "breakout",
    term: "Breakout",
    aliases: ["breakdown", "real breakdown"],
    category: "levels",
    level: "beginner",
    short: "Price closing beyond a level or pattern, ideally on strong volume, and staying there.",
    detail: ["Enter on the break, on the close, or on the retest: each trades missed moves against false signals."],
    related: ["fakeout", "retest", "liquidity-sweep"],
    lessonId: "u5-breakouts-fakeouts-and-retests",
  },
  {
    slug: "fakeout",
    term: "Fakeout",
    aliases: ["false breakout", "bull trap", "bear trap"],
    category: "levels",
    level: "beginner",
    short: "A break of a level that fails and falls back inside, trapping breakout traders.",
    detail: ["Smart Money traders read most fakeouts as liquidity sweeps."],
    related: ["breakout", "liquidity-sweep", "turtle-soup"],
    lessonId: "u5-breakouts-fakeouts-and-retests",
  },
  {
    slug: "retest",
    term: "Retest",
    category: "levels",
    level: "beginner",
    short: "Price returning to a level it just broke, often to test it from the other side.",
    detail: [],
    related: ["role-reversal", "breakout"],
    lessonId: "u5-breakouts-fakeouts-and-retests",
  },
  {
    slug: "fibonacci-retracement",
    term: "Fibonacci retracement",
    aliases: ["fib", "fibs", "61.8%", "golden ratio"],
    category: "levels",
    level: "intermediate",
    short: "Levels at 23.6%, 38.2%, 50%, 61.8% and 78.6% of a move, used to judge how deep a pullback might go.",
    detail: ["Draw from swing low to swing high in an uptrend. Levels work best when they line up with other evidence. 50% isn't a true Fibonacci ratio but is used anyway."],
    example: "A move from 50 to 150 has its 61.8% retracement at 150 − 61.8 = 88.2.",
    visual: "fibonacci",
    related: ["ote", "pullback", "fibonacci-extension"],
    lessonId: "u5-fibonacci-retracements-and-extensions",
  },
  {
    slug: "fibonacci-extension",
    term: "Fibonacci extension",
    aliases: ["127.2%", "161.8%"],
    category: "levels",
    level: "intermediate",
    short: "Levels beyond the old high (127.2%, 161.8%) used to estimate targets for the next leg.",
    detail: [],
    related: ["fibonacci-retracement", "measured-move", "take-profit"],
    lessonId: "u5-fibonacci-retracements-and-extensions",
  },
]
