import type { GlossaryTerm } from "@/lib/glossary/types"

export const MACRO: GlossaryTerm[] = [
  {
    slug: "economic-calendar",
    term: "Economic calendar",
    aliases: ["news calendar", "red folder"],
    category: "macro",
    level: "beginner",
    short: "A schedule of data releases and events with their time, expected impact, forecast, previous and actual values.",
    detail: [],
    related: ["consensus", "cpi", "nfp", "fomc"],
    lessonId: "u14-the-economic-calendar",
  },
  {
    slug: "consensus",
    term: "Consensus",
    aliases: ["forecast", "expectations", "surprise"],
    category: "macro",
    level: "beginner",
    short: "Economists' expected value for a release; markets react to the surprise between actual and consensus.",
    detail: [],
    example: "Inflation forecast 3.0%, actual 3.4%: a hot surprise.",
    related: ["priced-in", "economic-calendar"],
    lessonId: "u14-why-news-moves-price",
  },
  {
    slug: "priced-in",
    term: "Priced in",
    aliases: ["buy the rumour, sell the news"],
    category: "macro",
    level: "intermediate",
    short: "When an expected event is already reflected in the price before it happens.",
    detail: [],
    related: ["consensus", "earnings"],
    lessonId: "u14-why-news-moves-price",
  },
  {
    slug: "cpi",
    term: "CPI",
    aliases: ["consumer price index", "inflation", "core CPI"],
    category: "macro",
    level: "beginner",
    short: "The US inflation report, monthly at 8:30 am New York time; core CPI leaves out food and energy.",
    detail: ["A hot CPI makes rate hikes more likely: the dollar tends to rise, stocks and gold to fall."],
    example: "An index going from 300 to 309 in a year is 3% inflation.",
    related: ["interest-rate", "fomc", "economic-calendar"],
    lessonId: "u14-inflation-and-cpi",
  },
  {
    slug: "nfp",
    term: "Non-farm payrolls",
    aliases: ["NFP", "jobs report", "Employment Situation", "unemployment rate", "average hourly earnings"],
    category: "macro",
    level: "beginner",
    short: "The US jobs report, usually the first Friday of the month at 8:30 am New York time.",
    detail: ["It includes jobs added, the unemployment rate and wage growth. Earlier months get revised."],
    related: ["cpi", "economic-calendar"],
    lessonId: "u14-jobs-and-nfp",
  },
  {
    slug: "fomc",
    term: "FOMC",
    aliases: ["Federal Reserve", "Fed", "rate decision", "dot plot"],
    category: "macro",
    level: "beginner",
    short: "The Fed committee that sets US interest rates, eight times a year: decision at 2:00 pm, press conference at 2:30 pm.",
    detail: ["Four times a year it also publishes projections, including the dot plot of expected rates."],
    related: ["interest-rate", "central-bank", "cpi"],
    lessonId: "u14-rates-and-central-banks",
  },
  {
    slug: "interest-rate",
    term: "Interest rate",
    aliases: ["rate hike", "rate cut", "real rates", "real interest rates"],
    category: "macro",
    level: "beginner",
    short: "The price of money set by central banks; higher rates usually lift the currency and weigh on stocks and gold.",
    detail: [],
    related: ["fomc", "central-bank", "safe-haven"],
    lessonId: "u14-rates-and-central-banks",
  },
  {
    slug: "central-bank",
    term: "Central bank",
    aliases: ["ECB", "BoE", "BoJ"],
    category: "macro",
    level: "beginner",
    short: "The institution that sets a country's interest rates: the Fed, ECB, Bank of England, Bank of Japan and others.",
    detail: [],
    related: ["fomc", "interest-rate", "forex"],
    lessonId: "u14-rates-and-central-banks",
  },
  {
    slug: "earnings",
    term: "Earnings",
    aliases: ["EPS", "earnings season", "guidance", "revenue"],
    category: "macro",
    level: "beginner",
    short: "A company's quarterly results; the forecast for next quarter (guidance) often moves the stock most.",
    detail: ["Reports usually land before the open or after the close, so stocks often gap."],
    related: ["gap", "stock", "priced-in"],
    lessonId: "u14-earnings-and-crypto-drivers",
  },
  {
    slug: "halving",
    term: "Halving",
    aliases: ["Bitcoin halving"],
    category: "macro",
    level: "intermediate",
    short: "The cut in new Bitcoin issued per block, every 210,000 blocks (roughly every four years).",
    detail: [],
    related: ["cryptocurrency"],
    lessonId: "u14-earnings-and-crypto-drivers",
  },
  {
    slug: "safe-haven",
    term: "Safe haven",
    aliases: ["risk-off", "risk-on"],
    category: "macro",
    level: "intermediate",
    short: "Assets investors run to when scared, like gold, the yen and the Swiss franc (risk-off); the opposite mood is risk-on.",
    detail: [],
    related: ["commodity", "interest-rate"],
    lessonId: "u15-gold",
  },
  {
    slug: "dollar-index",
    term: "Dollar index",
    aliases: ["DXY", "US dollar index"],
    category: "macro",
    level: "intermediate",
    short: "A measure of the US dollar against a basket of major currencies; it often moves opposite to EUR/USD and gold.",
    detail: [],
    related: ["forex", "smt-divergence", "interest-rate"],
    lessonId: "u10-smt-divergence",
  },
]
