import type { GlossaryTerm } from "@/lib/glossary/types"

export const MARKETS: GlossaryTerm[] = [
  {
    slug: "stock",
    term: "Stock",
    aliases: ["share", "equity"],
    category: "markets",
    level: "beginner",
    short: "A small piece of ownership in a company, traded on an exchange.",
    detail: ["Stock prices move with the company's results, news about it, its sector and the mood of the whole market. US stocks trade mainly from 9:30 am to 4:00 pm New York time, with thinner pre-market and after-hours sessions."],
    related: ["index", "etf", "earnings", "pre-market"],
    lessonId: "u1-what-can-you-trade",
  },
  {
    slug: "index",
    term: "Index",
    aliases: ["indices", "S&P 500", "Nasdaq-100"],
    category: "markets",
    level: "beginner",
    short: "A single number that tracks a basket of stocks, like the S&P 500 or the Nasdaq-100.",
    detail: ["You can't buy an index itself. Traders use ETFs or index futures that follow it, such as **ES** for the S&P 500 and **NQ** for the Nasdaq-100."],
    related: ["etf", "futures-contract", "micro-futures", "stock"],
    lessonId: "u1-what-can-you-trade",
  },
  {
    slug: "etf",
    term: "ETF",
    aliases: ["exchange-traded fund"],
    category: "markets",
    level: "beginner",
    short: "A fund that trades on an exchange like a stock and tracks an index, sector, commodity or theme.",
    detail: ["ETFs let you buy a whole basket in one trade. Some track the S&P 500, others gold, a single sector or even Bitcoin."],
    related: ["index", "stock"],
  },
  {
    slug: "forex",
    term: "Forex",
    aliases: ["FX", "foreign exchange", "currency trading", "spot forex"],
    category: "markets",
    level: "beginner",
    short: "Trading one currency against another, quoted in pairs like EUR/USD.",
    detail: ["Forex is the largest market in the world and trades over the counter, 24 hours a day from Sunday evening to Friday evening New York time. It is busiest when London and New York overlap."],
    related: ["currency-pair", "pip", "lot", "otc", "swap"],
    lessonId: "u15-forex",
  },
  {
    slug: "currency-pair",
    term: "Currency pair",
    aliases: ["major", "cross", "exotic"],
    category: "markets",
    level: "beginner",
    short: "Two currencies quoted against each other; the price shows how much of the second buys one of the first.",
    detail: ["EUR/USD at 1.1000 means one euro costs 1.10 US dollars. **Majors** pair the dollar with another big currency, **crosses** leave the dollar out, and **exotics** include an emerging-market currency with wider spreads."],
    example: "Buying EUR/USD means going long euros and short dollars at the same time.",
    related: ["forex", "pip", "spread"],
    lessonId: "u15-forex",
  },
  {
    slug: "commodity",
    term: "Commodity",
    aliases: ["gold", "oil", "XAU/USD", "commodities", "GC"],
    category: "markets",
    level: "beginner",
    short: "A raw material such as gold, oil, silver or wheat, usually traded through futures or CFDs.",
    detail: ["Gold (XAU/USD, GC futures) is one of the most traded. It tends to react to real interest rates, the US dollar and fear in the markets."],
    related: ["futures-contract", "safe-haven", "cfd"],
    lessonId: "u15-gold",
  },
  {
    slug: "cryptocurrency",
    term: "Cryptocurrency",
    aliases: ["crypto", "Bitcoin", "BTC", "ETH"],
    category: "markets",
    level: "beginner",
    short: "Digital assets like Bitcoin and Ether that trade on crypto exchanges 24 hours a day, 7 days a week.",
    detail: ["Crypto is volatile and never closes. It can be traded spot (you own the coin) or through perpetual futures. Exchange risk, leverage and liquidation cascades are risks specific to crypto."],
    related: ["perpetual-futures", "funding-rate", "halving", "liquidation"],
    lessonId: "u15-crypto",
  },
  {
    slug: "futures-contract",
    term: "Futures contract",
    aliases: ["futures", "NQ", "ES", "roll", "rollover date"],
    category: "markets",
    level: "intermediate",
    short: "A standardised agreement to buy or sell something at a set price on a future date, traded on an exchange.",
    detail: ["Traders rarely hold futures to expiry; they trade the contract's price moves. Equity index futures expire quarterly (March, June, September, December), so positions get rolled to the next contract."],
    example: "One NQ contract gains or loses $20 for every point the Nasdaq-100 futures move.",
    related: ["micro-futures", "margin", "tick", "leverage"],
    lessonId: "u15-futures-and-indices",
  },
  {
    slug: "micro-futures",
    term: "Micro futures",
    aliases: ["MNQ", "MES", "MGC", "micros"],
    category: "markets",
    level: "intermediate",
    short: "Futures contracts one tenth the size of the standard ones, so smaller accounts can size positions properly.",
    detail: ["MNQ is worth $2 per point (NQ is $20) and MES $5 per point (ES is $50). Micro gold (MGC) is 10 ounces against the standard 100."],
    example: "A 50-point move on one MNQ contract is $100.",
    related: ["futures-contract", "position-sizing", "tick"],
    lessonId: "u2-leverage-and-margin",
    tool: { label: "Risk Calculator", href: "/dashboard/risk-calculator" },
  },
  {
    slug: "perpetual-futures",
    term: "Perpetual futures",
    aliases: ["perps", "perpetual swap"],
    category: "markets",
    level: "intermediate",
    short: "Crypto futures with no expiry date, kept close to the spot price by regular funding payments.",
    detail: ["Perps are the most traded crypto product. They allow high leverage, which is why fast moves can trigger chains of forced liquidations."],
    related: ["funding-rate", "liquidation", "cryptocurrency", "leverage"],
    lessonId: "u15-crypto",
  },
  {
    slug: "cfd",
    term: "CFD",
    aliases: ["contract for difference"],
    category: "markets",
    level: "intermediate",
    short: "A contract with your broker that pays the change in an asset's price; you never own the asset.",
    detail: ["CFDs are common in Europe, the UK and Australia but not allowed for US retail traders. European regulators found that 74% to 89% of retail CFD accounts typically lose money."],
    related: ["broker", "leverage", "otc"],
    lessonId: "u1-exchanges-brokers-and-otc",
  },
  {
    slug: "option",
    term: "Option",
    aliases: ["options", "call", "put"],
    category: "markets",
    level: "advanced",
    short: "A contract giving the right, but not the obligation, to buy (call) or sell (put) at a set price before a set date.",
    detail: ["Options are powerful and complex: their price depends on the underlying price, time and volatility. Entrix Academy only touches on them."],
    related: ["futures-contract", "leverage"],
    lessonId: "u1-what-can-you-trade",
  },
  {
    slug: "exchange",
    term: "Exchange",
    aliases: ["NYSE", "Nasdaq", "CME"],
    category: "markets",
    level: "beginner",
    short: "An organised marketplace where buy and sell orders meet in one central order book, under one set of rules.",
    detail: ["Everyone on the same exchange sees the same book and prices. One asset can trade on several exchanges, each with its own book. NYSE and Nasdaq list stocks, CME lists futures, and crypto exchanges list coins."],
    related: ["order-book", "broker", "otc"],
    lessonId: "u1-exchanges-brokers-and-otc",
  },
  {
    slug: "broker",
    term: "Broker",
    category: "markets",
    level: "beginner",
    short: "The company that gives you access to markets and sends your orders on for execution.",
    detail: ["Some brokers pass orders to an exchange; others, common in forex and CFDs, take the other side of your trades themselves. Always check that a broker is regulated where you live."],
    related: ["exchange", "otc", "cfd"],
    lessonId: "u1-exchanges-brokers-and-otc",
  },
  {
    slug: "otc",
    term: "OTC",
    aliases: ["over the counter"],
    category: "markets",
    level: "intermediate",
    short: "Trading directly between parties through dealers, with no single central exchange.",
    detail: ["Spot forex is OTC, so each dealer quotes its own prices. That is why two brokers' EUR/USD charts can differ by a fraction."],
    related: ["forex", "broker", "exchange"],
    lessonId: "u1-exchanges-brokers-and-otc",
  },
  {
    slug: "market-maker",
    term: "Market maker",
    aliases: ["liquidity provider"],
    category: "markets",
    level: "intermediate",
    short: "A firm that quotes both a buy and a sell price all day and earns the spread between them.",
    detail: ["Market makers are why you can almost always trade instantly. They pull back around big news, which is when spreads widen."],
    related: ["spread", "liquidity", "bid", "ask"],
    lessonId: "u1-who-is-on-the-other-side",
  },
  {
    slug: "institution",
    term: "Institution",
    aliases: ["institutional trader", "smart money", "fund"],
    category: "markets",
    level: "beginner",
    short: "A large professional participant, such as a pension fund, hedge fund or bank, that trades huge size.",
    detail: ["Big orders can't be filled at once without moving price, so institutions split them up and look for liquidity. That need is the core idea behind Smart Money Concepts."],
    related: ["retail-trader", "liquidity", "smart-money-concepts"],
    lessonId: "u1-who-is-on-the-other-side",
  },
  {
    slug: "retail-trader",
    term: "Retail trader",
    category: "markets",
    level: "beginner",
    short: "An individual trading their own money through a broker or app.",
    detail: ["Retail traders are many but small. Studies consistently show most lose money, mainly from too much risk, leverage and overtrading."],
    related: ["institution", "risk-per-trade", "overtrading"],
    lessonId: "u1-the-honest-numbers",
  },
  {
    slug: "hft",
    term: "High-frequency trading",
    aliases: ["HFT", "algo trading", "algorithms", "high-frequency traders"],
    category: "markets",
    level: "intermediate",
    short: "Computer programs that send and cancel orders in microseconds to capture tiny price differences.",
    detail: ["Humans can't compete on speed and don't need to: trading on minutes, hours or days makes microseconds irrelevant."],
    related: ["market-maker", "slippage"],
    lessonId: "u1-who-is-on-the-other-side",
  },
  {
    slug: "asset-class",
    term: "Asset class",
    aliases: ["asset classes"],
    category: "markets",
    level: "beginner",
    short: "A group of similar assets, such as stocks, indices, forex, commodities and crypto.",
    detail: ["Each behaves differently: when it trades, how far it moves and what pushes it around. Futures are contracts that follow these assets, not a class of their own."],
    related: ["stock", "forex", "commodity", "cryptocurrency"],
    lessonId: "u1-what-can-you-trade",
  },
  {
    slug: "hedger",
    term: "Hedger",
    aliases: ["hedgers", "hedging"],
    category: "markets",
    level: "intermediate",
    short: "A business that uses markets to reduce a risk it already has, rather than to bet on price.",
    detail: [],
    example: "An airline buys oil futures to lock in next year's fuel cost.",
    related: ["futures-contract", "institution"],
    lessonId: "u1-who-is-on-the-other-side",
  },
  {
    slug: "regulator",
    term: "Regulator",
    aliases: ["SEC", "CFTC", "NFA", "FINRA", "FCA", "ASIC", "ESMA"],
    category: "markets",
    level: "beginner",
    short: "A government body that licenses firms and polices markets, like the SEC and CFTC in the US or the FCA in the UK.",
    detail: ["Before sending money anywhere, look the firm up on its regulator's register, such as NFA BASIC or FINRA BrokerCheck."],
    related: ["broker", "exchange"],
    lessonId: "u1-regulation-and-scams",
  },
]
