import type { GlossaryTerm } from "@/lib/glossary/types"

export const ORDERS: GlossaryTerm[] = [
  {
    slug: "bid",
    term: "Bid",
    category: "orders",
    level: "beginner",
    short: "The highest price a buyer is willing to pay right now. You sell at the bid.",
    detail: ["Together with the ask, it forms the quote. When you sell at market, you receive the best bid."],
    related: ["ask", "spread", "order-book"],
    lessonId: "u2-bid-ask-and-spread",
  },
  {
    slug: "ask",
    term: "Ask",
    aliases: ["offer"],
    category: "orders",
    level: "beginner",
    short: "The lowest price a seller will accept right now. You buy at the ask.",
    detail: ["When you buy at market, you pay the best ask, which is always a little above the bid."],
    related: ["bid", "spread", "order-book"],
    lessonId: "u2-bid-ask-and-spread",
  },
  {
    slug: "spread",
    term: "Spread",
    aliases: ["bid-ask spread"],
    category: "orders",
    level: "beginner",
    short: "The gap between the ask and the bid; a cost you pay on every round trip.",
    detail: ["Liquid markets in busy hours have tight spreads. Thin markets, quiet hours and big news make them wider."],
    example: "Bid 50.10, ask 50.14: the spread is 0.04. On 100 shares, crossing it costs $4.",
    related: ["bid", "ask", "market-maker", "commission"],
    lessonId: "u2-bid-ask-and-spread",
  },
  {
    slug: "order-book",
    term: "Order book",
    aliases: ["depth", "DOM", "level 2"],
    category: "orders",
    level: "intermediate",
    short: "The live list of every waiting buy and sell order, with the size at each price.",
    detail: ["Asks sit above, bids below. A deep book absorbs big orders with little price change; a thin book jumps."],
    visual: "order-book",
    related: ["liquidity", "bid", "ask", "slippage"],
    lessonId: "u2-the-order-book-and-liquidity",
  },
  {
    slug: "market-order",
    term: "Market order",
    category: "orders",
    level: "beginner",
    short: "An order to fill immediately at the best available price: it guarantees the fill, not the price.",
    detail: ["If the best level doesn't have enough size, the order keeps filling at worse prices. That difference is slippage."],
    related: ["limit-order", "slippage", "order-book"],
    lessonId: "u2-market-orders-and-slippage",
  },
  {
    slug: "limit-order",
    term: "Limit order",
    category: "orders",
    level: "beginner",
    short: "An order to buy at a set price or lower, or sell at a set price or higher: it guarantees the price, not the fill.",
    detail: ["Limit orders rest in the order book until price reaches them. They are maker orders and often pay lower fees."],
    example: "Price is 100 and you want to buy only at 98: place a buy limit at 98.",
    related: ["market-order", "maker-taker", "stop-order"],
    lessonId: "u2-limit-orders",
  },
  {
    slug: "stop-order",
    term: "Stop order",
    aliases: ["stop-market", "stop", "sell stop", "buy stop"],
    category: "orders",
    level: "beginner",
    short: "An order that becomes a market order once price reaches your stop price.",
    detail: ["A sell stop below price protects a long; a buy stop above price protects a short or enters a breakout. In fast markets and gaps it can fill worse than the stop price."],
    related: ["stop-loss", "stop-limit-order", "slippage"],
    lessonId: "u2-stop-and-stop-limit-orders",
  },
  {
    slug: "stop-limit-order",
    term: "Stop-limit order",
    aliases: ["stop-limit"],
    category: "orders",
    level: "intermediate",
    short: "An order that places a limit order, instead of a market order, once the stop price is hit.",
    detail: ["It avoids terrible fills, but if price races through the limit it may not fill at all, which makes it risky as a stop-loss."],
    related: ["stop-order", "limit-order"],
    lessonId: "u2-stop-and-stop-limit-orders",
  },
  {
    slug: "slippage",
    term: "Slippage",
    category: "orders",
    level: "beginner",
    short: "The difference between the price you expected and the price you actually got.",
    detail: ["Slippage is worst on big orders, in thin markets, at session opens and around news."],
    example: "Market buy 300: 100 fill at 100.05 and 200 at 100.10, an average of about 100.08 instead of 100.05.",
    related: ["market-order", "order-book", "liquidity"],
    lessonId: "u2-market-orders-and-slippage",
  },
  {
    slug: "long",
    term: "Long",
    aliases: ["going long"],
    category: "orders",
    level: "beginner",
    short: "Buying first to sell later at a higher price; you profit if price rises.",
    detail: ["A long position can lose at most what was put in, because price can't fall below zero (leverage aside)."],
    related: ["short", "leverage"],
    lessonId: "u2-going-long-and-going-short",
  },
  {
    slug: "short",
    term: "Short",
    aliases: ["going short", "short selling"],
    category: "orders",
    level: "beginner",
    short: "Selling first to buy back later at a lower price; you profit if price falls.",
    detail: ["Stocks are shorted by borrowing shares. Futures, forex, CFDs and perps are simply sold. Short losses have no ceiling, so stops matter even more."],
    example: "Short 10 shares at $120 and cover at $112: profit $80 before costs.",
    related: ["long", "short-squeeze", "stop-loss"],
    lessonId: "u2-going-long-and-going-short",
  },
  {
    slug: "short-squeeze",
    term: "Short squeeze",
    category: "orders",
    level: "intermediate",
    short: "A sharp rally as short sellers rush to buy back at the same time, pushing price even higher.",
    detail: ["Crowded shorts plus a surprise rally is the classic recipe."],
    related: ["short", "liquidity-sweep"],
    lessonId: "u2-going-long-and-going-short",
  },
  {
    slug: "leverage",
    term: "Leverage",
    category: "orders",
    level: "beginner",
    short: "Controlling a position larger than your cash; it magnifies gains and losses equally.",
    detail: ["With stop-based position sizing, your risk is set by the stop and size, not by the leverage on offer. Leverage hurts when it tempts oversized positions."],
    example: "At 20:1, $1,000 controls $20,000, and a 5% move against you wipes out the $1,000.",
    related: ["margin", "margin-call", "liquidation", "position-sizing"],
    lessonId: "u2-leverage-and-margin",
  },
  {
    slug: "margin",
    term: "Margin",
    category: "orders",
    level: "beginner",
    short: "The deposit needed to open and hold a leveraged position.",
    detail: ["If losses push your account below the required maintenance margin, you get a margin call or your position is closed."],
    related: ["leverage", "margin-call", "liquidation"],
    lessonId: "u2-leverage-and-margin",
  },
  {
    slug: "margin-call",
    term: "Margin call",
    category: "orders",
    level: "intermediate",
    short: "A demand to add money because losses pushed your margin below the required level.",
    detail: ["Many platforms skip the call and close your position automatically."],
    related: ["margin", "liquidation", "leverage"],
    lessonId: "u2-leverage-and-margin",
  },
  {
    slug: "liquidation",
    term: "Liquidation",
    aliases: ["liquidation cascade"],
    category: "orders",
    level: "intermediate",
    short: "Your broker or exchange force-closing a leveraged position because your margin ran out.",
    detail: ["In crypto, one forced sale can push price into the next set of liquidations, a cascade that moves price fast with no news."],
    related: ["margin", "leverage", "perpetual-futures"],
    lessonId: "u15-crypto",
  },
  {
    slug: "pip",
    term: "Pip",
    aliases: ["pipette"],
    category: "orders",
    level: "beginner",
    short: "The standard unit of forex movement: 0.0001 for most pairs, 0.01 for yen pairs.",
    detail: ["A pipette is a tenth of a pip. On EUR/USD, one pip on a standard lot is worth about $10."],
    example: "EUR/USD from 1.0850 to 1.0875 is 25 pips: about $250 on one standard lot.",
    related: ["lot", "forex", "tick"],
    lessonId: "u2-pips-points-ticks-and-lots",
  },
  {
    slug: "lot",
    term: "Lot",
    aliases: ["standard lot", "mini lot", "micro lot"],
    category: "orders",
    level: "beginner",
    short: "A forex position size unit: standard 100,000, mini 10,000, micro 1,000 units.",
    detail: ["Position sizing in forex means choosing the lot size that makes your stop distance equal your planned risk."],
    related: ["pip", "position-sizing"],
    lessonId: "u2-pips-points-ticks-and-lots",
    tool: { label: "Risk Calculator", href: "/dashboard/risk-calculator" },
  },
  {
    slug: "tick",
    term: "Tick",
    aliases: ["point", "tick size", "tick value"],
    category: "orders",
    level: "intermediate",
    short: "The smallest price step a futures contract can move, worth a fixed dollar amount.",
    detail: ["NQ ticks in 0.25 points ($5), ES in 0.25 points ($12.50), gold (GC) in $0.10 ($10)."],
    example: "NQ moving 10 points is 40 ticks: $200 on one contract.",
    related: ["futures-contract", "micro-futures", "pip"],
    lessonId: "u2-pips-points-ticks-and-lots",
  },
  {
    slug: "commission",
    term: "Commission",
    category: "orders",
    level: "beginner",
    short: "The fee your broker charges per trade, contract or share.",
    detail: ["Small commissions add up fast with frequent trading. Always judge results after costs."],
    example: "$4 per round trip × 10 trades a day × 20 days = $800 a month.",
    related: ["spread", "slippage", "overtrading"],
    lessonId: "u2-what-trading-really-costs",
  },
  {
    slug: "swap",
    term: "Swap",
    aliases: ["rollover", "overnight financing"],
    category: "orders",
    level: "intermediate",
    short: "Interest charged or paid for holding a forex or CFD position past the daily rollover at 5 pm New York.",
    detail: ["It depends on the interest rate gap between the two currencies. Many brokers charge three days' swap on Wednesday to cover the weekend."],
    related: ["funding-rate", "forex", "cfd"],
    lessonId: "u2-what-trading-really-costs",
  },
  {
    slug: "funding-rate",
    term: "Funding rate",
    aliases: ["funding"],
    category: "orders",
    level: "intermediate",
    short: "Regular payments between longs and shorts on crypto perpetual futures that keep their price near spot.",
    detail: ["When perps trade above spot, longs usually pay shorts, and the other way round. Payments are often every 8 hours."],
    related: ["perpetual-futures", "swap"],
    lessonId: "u2-what-trading-really-costs",
  },
  {
    slug: "maker-taker",
    term: "Maker and taker",
    aliases: ["maker fee", "taker fee", "maker", "taker"],
    category: "orders",
    level: "intermediate",
    short: "Makers add liquidity with resting limit orders; takers remove it with market orders and often pay higher fees.",
    detail: [],
    related: ["limit-order", "market-order", "commission"],
    lessonId: "u2-limit-orders",
  },
]
