import type { GlossaryTerm } from "@/lib/glossary/types"

export const PSYCHOLOGY: GlossaryTerm[] = [
  {
    slug: "loss-aversion",
    term: "Loss aversion",
    aliases: ["prospect theory"],
    category: "psychology",
    level: "beginner",
    short: "Feeling a loss about twice as strongly as a gain of the same size (Kahneman and Tversky).",
    detail: ["It drives holding losers, moving stops and grabbing small wins. Decide stops and targets before entering and place them as orders."],
    related: ["disposition-effect", "stop-loss"],
    lessonId: "u13-loss-aversion",
  },
  {
    slug: "disposition-effect",
    term: "Disposition effect",
    aliases: ["cutting winners", "letting losers run"],
    category: "psychology",
    level: "intermediate",
    short: "Selling winners too early and holding losers too long; it can turn a winning strategy into a losing one.",
    detail: [],
    related: ["loss-aversion", "partial-profit", "trailing-stop"],
    lessonId: "u13-cutting-winners-early",
  },
  {
    slug: "fomo",
    term: "FOMO",
    aliases: ["fear of missing out", "chasing"],
    category: "psychology",
    level: "beginner",
    short: "The urge to jump into a move that is running away, usually with a poor entry and too much size.",
    detail: ["No setup, no trade. A missed trade costs nothing; a chased one usually costs."],
    related: ["revenge-trading", "overtrading"],
    lessonId: "u13-fomo",
  },
  {
    slug: "revenge-trading",
    term: "Revenge trading",
    category: "psychology",
    level: "beginner",
    short: "Trading to win back a loss right away, usually bigger and sloppier; small losses become big ones.",
    detail: [],
    related: ["daily-loss-limit", "tilt", "fomo"],
    lessonId: "u13-revenge-trading",
  },
  {
    slug: "overtrading",
    term: "Overtrading",
    aliases: ["overconfidence"],
    category: "psychology",
    level: "beginner",
    short: "Taking too many trades, often low-quality ones; studies find the most active traders tend to earn the least.",
    detail: [],
    related: ["commission", "fomo", "tilt"],
    lessonId: "u13-overconfidence-and-overtrading",
  },
  {
    slug: "tilt",
    term: "Tilt",
    category: "psychology",
    level: "beginner",
    short: "A state where emotion has taken over your decisions; the only good trade on tilt is no trade.",
    detail: [],
    related: ["revenge-trading", "daily-loss-limit"],
    lessonId: "u13-routines-discipline-and-tilt",
  },
  {
    slug: "confirmation-bias",
    term: "Confirmation bias",
    category: "psychology",
    level: "intermediate",
    short: "Noticing only the evidence that agrees with the trade you already want to take.",
    detail: ["Write down what would prove your bias wrong before the session, and look for it honestly."],
    related: ["bias", "trading-plan"],
    lessonId: "u13-routines-discipline-and-tilt",
  },
]
