import type { GlossaryTerm } from "@/lib/glossary/types"

const CALC = { label: "Risk Calculator", href: "/dashboard/risk-calculator" }

export const RISK: GlossaryTerm[] = [
  {
    slug: "risk-per-trade",
    term: "Risk per trade",
    aliases: ["1% rule", "one percent rule", "risk management"],
    category: "risk",
    level: "beginner",
    short: "The share of your account you can lose if a trade's stop is hit, usually 0.5% to 2%.",
    detail: ["Small fixed risk keeps normal losing streaks survivable. Ten 1% losses in a row cost under 10%."],
    example: "On a $25,000 account, 1% risk is $250 per trade.",
    related: ["position-sizing", "risk-of-ruin", "drawdown"],
    lessonId: "u11-the-1-rule",
    tool: CALC,
  },
  {
    slug: "position-sizing",
    term: "Position sizing",
    category: "risk",
    level: "beginner",
    short: "Choosing your size so that your stop distance costs exactly your planned risk.",
    detail: ["Size = money at risk ÷ (stop distance × value per unit). Place the stop first, then size; round down."],
    example: "$200 risk, entry $50, stop $48: 200 ÷ 2 = 100 shares.",
    related: ["risk-per-trade", "stop-loss", "lot", "micro-futures"],
    lessonId: "u11-position-sizing",
    tool: CALC,
  },
  {
    slug: "stop-loss",
    term: "Stop-loss",
    aliases: ["SL", "stop"],
    category: "risk",
    level: "beginner",
    short: "The price where your trade idea is proven wrong and you get out, placed as an order before you need it.",
    detail: ["Place it at structure (beyond the sweep or swing) or by volatility (ATR), not at an arbitrary amount. Stops only ever move towards profit."],
    related: ["stop-order", "atr", "position-sizing", "breakeven-stop"],
    lessonId: "u11-where-to-put-your-stop",
  },
  {
    slug: "take-profit",
    term: "Take-profit",
    aliases: ["TP", "target", "TP1", "TP2", "fixed target"],
    category: "risk",
    level: "beginner",
    short: "The price where you plan to close a winning trade, ideally at the next pool of liquidity.",
    detail: [],
    related: ["partial-profit", "risk-reward-ratio", "draw-on-liquidity"],
    lessonId: "u12-entries-and-exits",
  },
  {
    slug: "r-multiple",
    term: "R-multiple",
    aliases: ["R", "1R"],
    category: "risk",
    level: "intermediate",
    short: "A trade's result measured in units of what you risked: −1R is a full loss, +2R is twice your risk.",
    detail: [],
    example: "Buy 100, stop 98, exit 103: you risked 2 and made 3, so +1.5R.",
    related: ["risk-reward-ratio", "expectancy"],
    lessonId: "u11-r-multiples-and-reward-to-risk",
  },
  {
    slug: "risk-reward-ratio",
    term: "Risk to reward",
    aliases: ["R:R", "RR", "reward to risk"],
    category: "risk",
    level: "beginner",
    short: "The distance to your target compared with the distance to your stop, decided before entry.",
    detail: ["It only matters together with win rate: a 5:1 target that is rarely hit can still lose."],
    example: "Short 250, stop 254, target 238: 12 ÷ 4 = 3:1.",
    related: ["r-multiple", "win-rate", "breakeven-win-rate"],
    lessonId: "u11-r-multiples-and-reward-to-risk",
    tool: CALC,
  },
  {
    slug: "win-rate",
    term: "Win rate",
    aliases: ["hit rate", "strike rate"],
    category: "risk",
    level: "beginner",
    short: "The share of trades that end in profit; meaningless without the size of wins and losses.",
    detail: [],
    example: "18 wins and 27 losses is a 40% win rate.",
    related: ["expectancy", "breakeven-win-rate", "risk-reward-ratio"],
    lessonId: "u11-win-rate-r-r-and-expectancy",
  },
  {
    slug: "breakeven-win-rate",
    term: "Breakeven win rate",
    category: "risk",
    level: "intermediate",
    short: "The win rate at which a given reward to risk neither makes nor loses money: 1 ÷ (1 + R:R).",
    detail: [],
    example: "At 2:1 you need about 33% winners to break even; at 3:1 just 25%.",
    related: ["win-rate", "risk-reward-ratio", "expectancy"],
    lessonId: "u11-win-rate-r-r-and-expectancy",
  },
  {
    slug: "expectancy",
    term: "Expectancy",
    aliases: ["negative expectancy", "positive expectancy"],
    category: "risk",
    level: "intermediate",
    short: "What a strategy makes per trade on average: win rate × average win − loss rate × average loss.",
    detail: ["Positive expectancy after costs is the only thing that makes a strategy worth repeating."],
    example: "45% wins at 2R and 55% losses at 1R: 0.9 − 0.55 = +0.35R per trade.",
    related: ["edge", "win-rate", "r-multiple"],
    lessonId: "u11-win-rate-r-r-and-expectancy",
  },
  {
    slug: "drawdown",
    term: "Drawdown",
    aliases: ["max drawdown", "DD", "maximum drawdown"],
    category: "risk",
    level: "beginner",
    short: "A fall from your account's peak to a later low; recovering takes a bigger gain than the loss.",
    detail: ["Gain needed = loss ÷ (1 − loss). Cut risk during drawdowns, never raise it."],
    example: "A 20% drawdown needs a 25% gain; a 50% drawdown needs 100%.",
    visual: "drawdown",
    related: ["risk-of-ruin", "risk-per-trade", "daily-loss-limit"],
    lessonId: "u11-drawdown-math",
  },
  {
    slug: "risk-of-ruin",
    term: "Risk of ruin",
    aliases: ["losing streak"],
    category: "risk",
    level: "intermediate",
    short: "The chance a strategy loses so much you can't or won't continue; driven mostly by risk per trade.",
    detail: ["With a 40% win rate, 8 or 9 losses in a row will happen. Plan for it."],
    example: "With a 50% win rate, the chance of the next 4 trades all losing is 6.25%.",
    related: ["drawdown", "risk-per-trade", "daily-loss-limit"],
    lessonId: "u11-risk-of-ruin",
  },
  {
    slug: "daily-loss-limit",
    term: "Daily loss limit",
    aliases: ["max daily loss", "circuit breaker", "weekly loss limit"],
    category: "risk",
    level: "beginner",
    short: "A hard cap on how much you can lose in a day; hit it and you stop trading until tomorrow.",
    detail: [],
    related: ["revenge-trading", "risk-of-ruin", "prop-firm"],
    lessonId: "u11-risk-of-ruin",
  },
  {
    slug: "correlation",
    term: "Correlation",
    category: "risk",
    level: "intermediate",
    short: "How closely two markets move together; positions in correlated markets are really one bigger bet.",
    detail: [],
    example: "Long NQ at 1% risk and long ES at 1% is effectively 2% on one idea.",
    related: ["risk-per-trade", "smt-divergence"],
    lessonId: "u11-leverage-and-correlation",
  },
  {
    slug: "breakeven-stop",
    term: "Breakeven stop",
    aliases: ["BE", "stop to breakeven", "breakeven"],
    category: "risk",
    level: "intermediate",
    short: "Moving your stop to your entry once a trade is in profit, so it can no longer lose.",
    detail: ["Too early, and normal pullbacks stop out trades that would have hit target. Test when to do it."],
    related: ["trailing-stop", "stop-loss", "partial-profit"],
    lessonId: "u12-entries-and-exits",
  },
  {
    slug: "trailing-stop",
    term: "Trailing stop",
    category: "risk",
    level: "intermediate",
    short: "A stop that follows price in your favour, behind new swing points or by an ATR multiple.",
    detail: [],
    related: ["breakeven-stop", "atr", "stop-loss"],
    lessonId: "u12-entries-and-exits",
  },
  {
    slug: "partial-profit",
    term: "Partial profit",
    aliases: ["partials", "scaling out"],
    category: "risk",
    level: "intermediate",
    short: "Closing part of a position at a first target and letting the rest run.",
    detail: [],
    example: "Half closed at +1R and half at +3R averages +2R.",
    related: ["take-profit", "breakeven-stop"],
    lessonId: "u12-entries-and-exits",
  },
]
