import type { GlossaryTerm } from "@/lib/glossary/types"

export const SMC: GlossaryTerm[] = [
  {
    slug: "smart-money-concepts",
    term: "Smart Money Concepts",
    aliases: ["SMC"],
    category: "smc",
    level: "intermediate",
    short: "A framework that reads charts through liquidity, imbalances and the footprints of large traders.",
    detail: ["It is one of the most popular ways retail traders read charts today. Treat it as a framework to test, not proven truth: there is little formal research on it."],
    related: ["ict", "liquidity", "order-block", "fair-value-gap"],
    lessonId: "u7-what-liquidity-means-in-smc",
  },
  {
    slug: "ict",
    term: "ICT",
    aliases: ["Inner Circle Trader"],
    category: "smc",
    level: "intermediate",
    short: "The trader whose teachings popularised fair value gaps, killzones, Power of 3, OTE and many other SMC terms.",
    detail: [],
    related: ["smart-money-concepts", "killzone", "power-of-3", "silver-bullet"],
    lessonId: "u7-what-liquidity-means-in-smc",
  },
  {
    slug: "liquidity",
    term: "Liquidity",
    aliases: ["liquidity pool", "resting orders"],
    category: "smc",
    level: "intermediate",
    short: "In SMC, the pools of resting orders, especially stop-losses, that sit beyond obvious highs and lows.",
    detail: ["Large traders need lots of orders to fill size against, so price is often drawn to these pools. In the classic sense, liquidity also means how easily you can trade without moving price."],
    visual: "liquidity",
    related: ["buy-side-liquidity", "sell-side-liquidity", "liquidity-sweep", "order-book"],
    lessonId: "u7-what-liquidity-means-in-smc",
  },
  {
    slug: "buy-side-liquidity",
    term: "Buy-side liquidity",
    aliases: ["BSL"],
    category: "smc",
    level: "intermediate",
    short: "Buy orders resting above highs: short sellers' stop-losses and breakout traders' buy stops.",
    detail: [],
    related: ["sell-side-liquidity", "liquidity", "equal-highs-lows"],
    lessonId: "u7-buy-side-and-sell-side-liquidity",
  },
  {
    slug: "sell-side-liquidity",
    term: "Sell-side liquidity",
    aliases: ["SSL"],
    category: "smc",
    level: "intermediate",
    short: "Sell orders resting below lows: long traders' stop-losses and breakdown sell stops.",
    detail: [],
    related: ["buy-side-liquidity", "liquidity", "equal-highs-lows"],
    lessonId: "u7-buy-side-and-sell-side-liquidity",
  },
  {
    slug: "equal-highs-lows",
    term: "Equal highs and lows",
    aliases: ["EQH", "EQL", "relative equal highs", "double top liquidity", "equal highs", "equal lows"],
    category: "smc",
    level: "intermediate",
    short: "Two or more highs (or lows) at almost the same price: an obvious pool of stops that tends to get taken.",
    detail: [],
    visual: "equal-lows",
    related: ["liquidity-sweep", "double-top", "buy-side-liquidity"],
    lessonId: "u7-equal-highs-equal-lows-and-trendline-liquidity",
  },
  {
    slug: "trendline-liquidity",
    term: "Trendline liquidity",
    category: "smc",
    level: "advanced",
    short: "The row of stops that builds up just beyond a clean, many-touch trendline.",
    detail: [],
    related: ["trendline", "liquidity"],
    lessonId: "u7-equal-highs-equal-lows-and-trendline-liquidity",
  },
  {
    slug: "liquidity-sweep",
    term: "Liquidity sweep",
    aliases: ["sweep", "raid", "run on stops", "liquidity grab"],
    category: "smc",
    level: "intermediate",
    short: "Price wicking through an obvious high or low to take the stops, then closing back inside and reversing.",
    detail: ["A real breakout closes beyond the level and holds there; a sweep spends little time beyond it. Wait for displacement and a structure shift to confirm."],
    visual: "sweep",
    related: ["stop-hunt", "fakeout", "market-structure-shift", "turtle-soup"],
    lessonId: "u7-sweeps-vs-real-breakouts",
  },
  {
    slug: "stop-hunt",
    term: "Stop hunt",
    category: "smc",
    level: "intermediate",
    short: "A move that runs the stops clustered at an obvious level before price turns.",
    detail: ["It is less a villain hunting you than large orders going where liquidity is."],
    related: ["liquidity-sweep", "turtle-soup", "round-number"],
    lessonId: "u7-stop-hunts-and-turtle-soup",
  },
  {
    slug: "inducement",
    term: "Inducement",
    aliases: ["IDM"],
    category: "smc",
    level: "advanced",
    short: "An early, obvious level in front of the real point of interest that lures traders in too soon.",
    detail: ["Their stops become liquidity that price takes on its way to the deeper zone. Many SMC traders wait for the inducement to be swept first."],
    related: ["point-of-interest", "liquidity-sweep"],
    lessonId: "u7-inducement",
  },
  {
    slug: "external-range-liquidity",
    term: "External range liquidity",
    aliases: ["ERL", "internal range liquidity", "IRL"],
    category: "smc",
    level: "advanced",
    short: "Liquidity beyond the range's swing highs and lows (ERL), as opposed to internal liquidity like fair value gaps inside it (IRL).",
    detail: ["ICT's idea: price moves from external to internal liquidity and back."],
    related: ["fair-value-gap", "dealing-range", "liquidity"],
    lessonId: "u7-internal-vs-external-range-liquidity",
  },
  {
    slug: "liquidity-void",
    term: "Liquidity void",
    category: "smc",
    level: "advanced",
    short: "A stretch price crossed so fast and one-sidedly that little trading happened there; often revisited later.",
    detail: [],
    related: ["fair-value-gap", "displacement", "volume-profile"],
    lessonId: "u7-liquidity-voids",
  },
  {
    slug: "displacement",
    term: "Displacement",
    category: "smc",
    level: "intermediate",
    short: "A fast, large-bodied move with little wick that shows intent, breaks structure and leaves fair value gaps.",
    detail: [],
    visual: "displacement",
    related: ["fair-value-gap", "market-structure-shift", "impulse"],
    lessonId: "u8-displacement",
  },
  {
    slug: "fair-value-gap",
    term: "Fair value gap",
    aliases: ["FVG", "imbalance", "BISI", "SIBI", "bullish FVG", "bearish FVG"],
    category: "smc",
    level: "intermediate",
    short: "A three-candle gap where candle 1's wick and candle 3's wick don't overlap, left by a fast move.",
    detail: ["Bullish FVG (BISI): candle 1's high to candle 3's low. Bearish FVG (SIBI): candle 1's low to candle 3's high. Price often returns to rebalance the gap; context decides which gaps matter."],
    example: "Candle 1 high 100.9, candle 3 low 102.0: a 1.1-point bullish gap.",
    visual: "fvg",
    related: ["consequent-encroachment", "inverse-fvg", "displacement", "mss-fvg-entry"],
    lessonId: "u8-fair-value-gaps",
  },
  {
    slug: "consequent-encroachment",
    term: "Consequent encroachment",
    aliases: ["CE", "50% of the gap"],
    category: "smc",
    level: "advanced",
    short: "The 50% level of a fair value gap (or of a long wick); healthy gaps tend to hold it.",
    detail: [],
    example: "A bullish FVG from 103.2 to 104.1 has its CE at 103.65.",
    related: ["fair-value-gap", "mean-threshold"],
    lessonId: "u8-consequent-encroachment",
  },
  {
    slug: "inverse-fvg",
    term: "Inverse fair value gap",
    aliases: ["IFVG", "iFVG"],
    category: "smc",
    level: "advanced",
    short: "A fair value gap that price closed straight through; it flips and acts in the opposite direction.",
    detail: [],
    related: ["fair-value-gap", "breaker-block"],
    lessonId: "u8-inverse-fair-value-gaps",
  },
  {
    slug: "volume-imbalance",
    term: "Volume imbalance",
    aliases: ["VI"],
    category: "smc",
    level: "advanced",
    short: "A gap between two neighbouring candles' bodies while their wicks still overlap.",
    detail: [],
    related: ["fair-value-gap", "balanced-price-range"],
    lessonId: "u8-volume-imbalance-and-balanced-price-range",
  },
  {
    slug: "balanced-price-range",
    term: "Balanced price range",
    aliases: ["BPR"],
    category: "smc",
    level: "advanced",
    short: "The overlap of a bullish and a bearish fair value gap, where price moved fast both ways.",
    detail: [],
    related: ["fair-value-gap", "volume-imbalance"],
    lessonId: "u8-volume-imbalance-and-balanced-price-range",
  },
  {
    slug: "order-block",
    term: "Order block",
    aliases: ["OB", "bullish order block", "bearish order block"],
    category: "smc",
    level: "intermediate",
    short: "The last opposite-coloured candle before a displacement that breaks structure; price often reacts when it returns.",
    detail: ["Bullish OB: last down-close candle before a move up. The SMC checklist: it took liquidity, the move left an FVG, it broke structure, and it is still unmitigated."],
    visual: "order-block",
    related: ["mean-threshold", "breaker-block", "demand-zone", "point-of-interest"],
    lessonId: "u8-order-blocks",
  },
  {
    slug: "mean-threshold",
    term: "Mean threshold",
    category: "smc",
    level: "advanced",
    short: "The 50% level of an order block's body.",
    detail: [],
    related: ["order-block", "consequent-encroachment"],
    lessonId: "u8-order-blocks",
  },
  {
    slug: "breaker-block",
    term: "Breaker block",
    aliases: ["breaker", "bullish breaker", "bearish breaker"],
    category: "smc",
    level: "advanced",
    short: "An order block that failed after a liquidity sweep and flipped: a broken bearish block becomes bullish support.",
    detail: ["Sequence for a bullish breaker: swing high, a drop that sweeps an old low, then a close back up through the bearish order block at the swing high."],
    visual: "breaker",
    related: ["mitigation-block", "order-block", "unicorn"],
    lessonId: "u8-breaker-and-mitigation-blocks",
  },
  {
    slug: "mitigation-block",
    term: "Mitigation block",
    category: "smc",
    level: "advanced",
    short: "Like a breaker, a failed order block that flips, but formed without a liquidity sweep.",
    detail: [],
    related: ["breaker-block", "order-block"],
    lessonId: "u8-breaker-and-mitigation-blocks",
  },
  {
    slug: "rejection-block",
    term: "Rejection block",
    aliases: ["propulsion block"],
    category: "smc",
    level: "advanced",
    short: "The long wick at a swing point, from the wick's extreme to the body; a propulsion block is an order block formed on top of an older one.",
    detail: [],
    related: ["wick", "order-block", "consequent-encroachment"],
    lessonId: "u8-rejection-and-propulsion-blocks",
  },
  {
    slug: "point-of-interest",
    term: "Point of interest",
    aliases: ["POI"],
    category: "smc",
    level: "intermediate",
    short: "Any zone you might trade from: a fair value gap, order block, breaker and so on.",
    detail: ["Rank them by timeframe, alignment with the bias, liquidity taken, displacement, freshness and premium or discount."],
    related: ["order-block", "fair-value-gap", "confluence"],
    lessonId: "u8-ranking-points-of-interest",
  },
  {
    slug: "dealing-range",
    term: "Dealing range",
    category: "smc",
    level: "advanced",
    short: "The range between the swing low and swing high of the current leg, usually the one that broke structure.",
    detail: [],
    related: ["premium-discount", "external-range-liquidity"],
    lessonId: "u9-dealing-ranges",
  },
  {
    slug: "premium-discount",
    term: "Premium and discount",
    aliases: ["equilibrium", "EQ", "premium", "discount", "in discount"],
    category: "smc",
    level: "intermediate",
    short: "Above the 50% (equilibrium) of the dealing range is premium, below it is discount: buy in discount, sell in premium.",
    detail: [],
    example: "A range from 100 to 110 has equilibrium at 105.",
    visual: "premium-discount",
    related: ["dealing-range", "ote"],
    lessonId: "u9-premium-discount-and-equilibrium",
  },
  {
    slug: "ote",
    term: "Optimal trade entry",
    aliases: ["OTE", "70.5%"],
    category: "smc",
    level: "advanced",
    short: "ICT's entry zone between the 62% and 79% retracement of a leg, with 70.5% as the sweet spot.",
    detail: ["Deep entries keep stops small and targets large, but not every pullback reaches OTE."],
    example: "A leg from 100 to 110 has its 70.5% retracement at 102.95.",
    visual: "ote",
    related: ["fibonacci-retracement", "premium-discount"],
    lessonId: "u9-optimal-trade-entry",
  },
  {
    slug: "draw-on-liquidity",
    term: "Draw on liquidity",
    aliases: ["DOL", "draw"],
    category: "smc",
    level: "advanced",
    short: "The pool of liquidity or imbalance price is most likely heading for next, which sets your bias.",
    detail: [],
    related: ["bias", "buy-side-liquidity", "fair-value-gap"],
    lessonId: "u10-bias-and-draw-on-liquidity",
  },
  {
    slug: "mss-fvg-entry",
    term: "MSS and FVG entry",
    aliases: ["2022 model", "core ICT model"],
    category: "smc",
    level: "advanced",
    short: "Sweep liquidity, displace into a structure shift, then enter on the retrace into the fair value gap it left.",
    detail: ["Stop beyond the sweep; target the opposite liquidity. If price never returns to your limit order, let it go."],
    related: ["market-structure-shift", "fair-value-gap", "liquidity-sweep", "silver-bullet"],
    lessonId: "u10-the-mss-and-fvg-entry",
  },
  {
    slug: "silver-bullet",
    term: "Silver Bullet",
    category: "smc",
    level: "advanced",
    short: "ICT's one-hour model: an FVG entry toward the draw on liquidity inside 3-4 am, 10-11 am or 2-3 pm New York time.",
    detail: [],
    related: ["mss-fvg-entry", "killzone", "draw-on-liquidity"],
    lessonId: "u10-silver-bullet",
  },
  {
    slug: "unicorn",
    term: "Unicorn model",
    aliases: ["unicorn"],
    category: "smc",
    level: "advanced",
    short: "A breaker block overlapping a same-direction fair value gap; the overlap is the entry zone.",
    detail: [],
    related: ["breaker-block", "fair-value-gap", "confluence"],
    lessonId: "u10-unicorn-model",
  },
  {
    slug: "turtle-soup",
    term: "Turtle soup",
    category: "smc",
    level: "advanced",
    short: "Fading a failed run above an obvious high (or below a low) once price fails back inside and shifts structure.",
    detail: ["The name comes from Raschke and Connors' 1995 setup that faded failed 20-day breakouts."],
    related: ["liquidity-sweep", "stop-hunt", "fakeout"],
    lessonId: "u10-turtle-soup-reversal",
  },
  {
    slug: "smt-divergence",
    term: "SMT divergence",
    aliases: ["SMT", "smart money technique"],
    category: "smc",
    level: "advanced",
    short: "Correlated markets disagreeing at a key level, for example NQ making a lower low while ES doesn't.",
    detail: ["It is a confirmation for a sweep, not an entry on its own."],
    related: ["divergence", "liquidity-sweep", "correlation"],
    lessonId: "u10-smt-divergence",
  },
  {
    slug: "market-maker-model",
    term: "Market maker model",
    aliases: ["MMBM", "MMSM", "smart money reversal", "sell-side curve", "buy-side curve", "original consolidation"],
    category: "smc",
    level: "advanced",
    short: "ICT's big-picture cycle: consolidation, a stair-step move one way, a reversal at a key level, and a stair-step return.",
    detail: [],
    related: ["draw-on-liquidity", "power-of-3"],
    lessonId: "u10-market-maker-models",
  },
  {
    slug: "power-of-3",
    term: "Power of 3",
    aliases: ["AMD", "PO3", "accumulation manipulation distribution", "manipulation"],
    category: "smc",
    level: "advanced",
    short: "ICT's idea that a candle forms in three phases: accumulation, manipulation (a false move) and distribution (the real move).",
    detail: ["On a bullish day the manipulation usually dips below the open before the rally."],
    visual: "judas",
    related: ["judas-swing", "wyckoff", "midnight-open"],
    lessonId: "u9-power-of-3-and-the-judas-swing",
  },
  {
    slug: "judas-swing",
    term: "Judas swing",
    category: "smc",
    level: "advanced",
    short: "The early false move of the session, against the day's real direction, that runs stops before reversing.",
    detail: [],
    visual: "judas",
    related: ["power-of-3", "asian-range", "liquidity-sweep"],
    lessonId: "u9-power-of-3-and-the-judas-swing",
  },
  {
    slug: "wyckoff",
    term: "Wyckoff method",
    aliases: ["spring", "accumulation", "distribution", "composite man", "Richard Wyckoff", "markup", "selling climax", "automatic rally", "secondary test", "sign of strength", "last point of support"],
    category: "smc",
    level: "advanced",
    short: "Richard Wyckoff's early 1900s model of accumulation and distribution ranges; his spring is SMC's liquidity sweep.",
    detail: ["Watch the word distribution: in Wyckoff it is a topping range, in ICT's AMD it is the day's real move."],
    visual: "spring",
    related: ["power-of-3", "liquidity-sweep", "dow-theory"],
    lessonId: "u9-wyckoff-the-roots-of-amd",
  },
]
