import type { GlossaryTerm } from "@/lib/glossary/types"

export const STRATEGY: GlossaryTerm[] = [
  {
    slug: "edge",
    term: "Edge",
    category: "strategy",
    level: "beginner",
    short: "A repeatable advantage that makes more than it loses over many trades, after costs.",
    detail: ["Without an edge and risk control, trading works like a casino game with the house edge against you."],
    related: ["expectancy", "backtesting", "sample-size"],
    lessonId: "u1-trading-vs-investing-vs-gambling",
  },
  {
    slug: "bias",
    term: "Bias",
    aliases: ["directional bias", "daily bias", "HTF bias"],
    category: "strategy",
    level: "intermediate",
    short: "Your working assumption of direction, usually from the higher timeframe; you trade with it and update it when structure says so.",
    detail: [],
    related: ["draw-on-liquidity", "multi-timeframe-analysis"],
    lessonId: "u10-bias-and-draw-on-liquidity",
  },
  {
    slug: "trading-plan",
    term: "Trading plan",
    category: "strategy",
    level: "beginner",
    short: "A short written document of what, when and how you trade, with your risk limits and routines.",
    detail: ["Write it when calm, follow it when not, and change it only outside market hours on real evidence."],
    related: ["setup-trigger", "daily-loss-limit", "journal"],
    lessonId: "u12-writing-a-trading-plan",
  },
  {
    slug: "setup-trigger",
    term: "Setup and trigger",
    aliases: ["setup", "trigger", "entry criteria", "management"],
    category: "strategy",
    level: "beginner",
    short: "The setup is when conditions are worth trading; the trigger is the exact event that gets you in.",
    detail: [],
    related: ["trading-plan", "mss-fvg-entry"],
    lessonId: "u12-setup-trigger-and-management",
  },
  {
    slug: "backtesting",
    term: "Backtesting",
    aliases: ["backtest", "bar replay", "cherry-picking"],
    category: "strategy",
    level: "intermediate",
    short: "Applying exact rules to past data, trade by trade, to see whether an idea has an edge.",
    detail: ["Log every setup, hide the right side of the chart, include costs, and keep some data back for an out-of-sample check."],
    related: ["overfitting", "look-ahead-bias", "forward-testing", "sample-size"],
    lessonId: "u12-honest-backtesting",
  },
  {
    slug: "forward-testing",
    term: "Forward testing",
    aliases: ["paper trading", "demo account", "demo"],
    category: "strategy",
    level: "intermediate",
    short: "Trading a strategy in real time, first on demo and then with very small size, before scaling up.",
    detail: [],
    related: ["backtesting", "sample-size"],
    lessonId: "u12-forward-testing",
  },
  {
    slug: "overfitting",
    term: "Overfitting",
    aliases: ["curve fitting", "in-sample", "out-of-sample"],
    category: "strategy",
    level: "advanced",
    short: "Tweaking rules until they fit the past perfectly, so they fail on new data.",
    detail: [],
    related: ["backtesting", "look-ahead-bias"],
    lessonId: "u12-honest-backtesting",
  },
  {
    slug: "look-ahead-bias",
    term: "Look-ahead bias",
    aliases: ["hindsight bias", "survivorship bias", "hindsight"],
    category: "strategy",
    level: "advanced",
    short: "Using information you couldn't have had at the time, such as a candle that hadn't closed yet.",
    detail: ["Its cousin, survivorship bias, is testing only on assets that still exist today."],
    related: ["backtesting", "overfitting"],
    lessonId: "u12-honest-backtesting",
  },
  {
    slug: "sample-size",
    term: "Sample size",
    category: "strategy",
    level: "intermediate",
    short: "How many trades your conclusions rest on; under about 30 is mostly noise, aim for 50 to 100 or more.",
    detail: [],
    example: "A strategy that truly wins 50% has about a 13% chance of winning 7 or fewer of its next 20 trades.",
    related: ["backtesting", "win-rate"],
    lessonId: "u12-sample-size-and-when-to-change",
  },
  {
    slug: "journal",
    term: "Trading journal",
    aliases: ["journal", "trade log", "Trade Journal"],
    category: "strategy",
    level: "beginner",
    short: "A record of every trade, with context and behaviour, used to find what works and what you keep getting wrong.",
    detail: [],
    related: ["trading-plan", "weekly-review"],
    lessonId: "u12-journaling",
    tool: { label: "Trade Journal", href: "/dashboard/trade-journal" },
  },
  {
    slug: "weekly-review",
    term: "Weekly review",
    aliases: ["Trade Calendar"],
    category: "strategy",
    level: "beginner",
    short: "A weekly look at your numbers, rule breaks and best and worst trades, ending in one change to make.",
    detail: [],
    related: ["journal", "trading-plan"],
    lessonId: "u12-the-weekly-review",
    tool: { label: "Trade Calendar", href: "/dashboard/trade-calendar" },
  },
  {
    slug: "prop-firm",
    term: "Prop firm",
    aliases: ["funded account", "evaluation", "challenge", "prop firm evaluation"],
    category: "strategy",
    level: "intermediate",
    short: "A company that lets you trade its capital after paying for and passing an evaluation with strict loss limits.",
    detail: ["Read the rules carefully: most participants don't pass."],
    related: ["daily-loss-limit", "drawdown"],
    lessonId: "u15-futures-and-indices",
  },
  {
    slug: "trading-style",
    term: "Trading style",
    aliases: ["scalping", "day trading", "swing trading", "position trading"],
    category: "strategy",
    level: "beginner",
    short: "How long you hold trades: scalping (minutes), day trading (flat by the close), swing (days to weeks), position (weeks to months).",
    detail: ["Shorter styles need more screen time and pay more in costs relative to their targets."],
    related: ["timeframe", "commission"],
    lessonId: "u15-choosing-your-style",
  },
  {
    slug: "confirmation",
    term: "Confirmation",
    aliases: ["confirmed"],
    category: "strategy",
    level: "beginner",
    short: "Waiting for extra evidence, like a close beyond a level, before acting; fewer false signals but a later entry.",
    detail: [],
    related: ["setup-trigger", "break-of-structure", "breakout"],
    lessonId: "u3-candles-in-context",
  },
]
