import type { GlossaryTerm } from "@/lib/glossary/types"

export const STRUCTURE: GlossaryTerm[] = [
  {
    slug: "swing-high",
    term: "Swing high",
    aliases: ["swing low", "swing point", "fractal"],
    category: "structure",
    level: "beginner",
    short: "A turning point whose high is above the highs on both sides (a swing low is the mirror).",
    detail: ["A common rule uses two candles on each side. Swing points are the skeleton every structure method is built on."],
    related: ["higher-high-higher-low", "break-of-structure", "liquidity"],
    lessonId: "u4-swing-highs-and-swing-lows",
  },
  {
    slug: "higher-high-higher-low",
    term: "Higher high and higher low",
    aliases: ["HH", "HL", "uptrend", "higher low", "last higher low", "higher high"],
    category: "structure",
    level: "beginner",
    short: "Each peak above the last and each dip above the last: the definition of an uptrend.",
    detail: ["The latest higher low is the level buyers must defend to keep the trend alive."],
    visual: "uptrend",
    related: ["lower-high-lower-low", "break-of-structure", "change-of-character"],
    lessonId: "u4-trend-vs-range",
  },
  {
    slug: "lower-high-lower-low",
    term: "Lower high and lower low",
    aliases: ["LH", "LL", "downtrend", "lower high", "lower low"],
    category: "structure",
    level: "beginner",
    short: "Each rally peaking lower and each drop going further: the definition of a downtrend.",
    detail: [],
    related: ["higher-high-higher-low", "break-of-structure"],
    lessonId: "u4-trend-vs-range",
  },
  {
    slug: "range",
    term: "Range",
    aliases: ["consolidation", "sideways market"],
    category: "structure",
    level: "beginner",
    short: "Price bouncing between similar highs and lows with neither side in control.",
    detail: ["Range edges collect stops on both sides, so they are prime liquidity for breakouts and sweeps."],
    related: ["support", "resistance", "breakout", "liquidity-sweep"],
    lessonId: "u4-trend-vs-range",
  },
  {
    slug: "impulse",
    term: "Impulse",
    aliases: ["impulse leg"],
    category: "structure",
    level: "beginner",
    short: "A fast move in the direction of the trend, with big candles covering a lot of ground.",
    detail: ["Healthy trends have impulses that are longer and faster than the pullbacks between them."],
    related: ["pullback", "displacement"],
    lessonId: "u4-impulse-and-pullback",
  },
  {
    slug: "pullback",
    term: "Pullback",
    aliases: ["retracement", "correction"],
    category: "structure",
    level: "beginner",
    short: "A slower move against the trend between impulses; where many traders look for entries.",
    detail: [],
    related: ["impulse", "fibonacci-retracement", "ote"],
    lessonId: "u4-impulse-and-pullback",
  },
  {
    slug: "break-of-structure",
    term: "Break of structure",
    aliases: ["BOS"],
    category: "structure",
    level: "intermediate",
    short: "A close beyond the last swing point in the direction of the trend, confirming the trend continues.",
    detail: ["Use closes, not wicks. A wick beyond the level that falls back can be a liquidity sweep instead."],
    visual: "bos",
    related: ["change-of-character", "market-structure-shift", "swing-high"],
    lessonId: "u4-break-of-structure",
  },
  {
    slug: "change-of-character",
    term: "Change of character",
    aliases: ["CHoCH", "CHOCH"],
    category: "structure",
    level: "intermediate",
    short: "The first close against the trend through its last protected swing, an early sign the trend may be turning.",
    detail: ["In an uptrend it is a close below the last higher low. Traders usually wait for a lower high and a break of structure down to confirm."],
    visual: "choch",
    related: ["break-of-structure", "market-structure-shift"],
    lessonId: "u4-change-of-character",
  },
  {
    slug: "market-structure-shift",
    term: "Market structure shift",
    aliases: ["MSS"],
    category: "structure",
    level: "advanced",
    short: "ICT's stricter change of character: a break against the trend that comes with displacement, often right after a liquidity sweep.",
    detail: ["It is the trigger in most ICT entry models."],
    related: ["change-of-character", "displacement", "liquidity-sweep", "mss-fvg-entry"],
    lessonId: "u4-change-of-character",
  },
  {
    slug: "internal-structure",
    term: "Internal structure",
    aliases: ["swing structure", "minor structure"],
    category: "structure",
    level: "advanced",
    short: "The smaller zigzag inside one swing leg, as opposed to the major swing structure.",
    detail: ["Internal breaks happen constantly; swing breaks carry the weight. Take direction from swing structure and timing from internal structure."],
    related: ["strong-low-weak-high", "change-of-character"],
    lessonId: "u4-internal-vs-swing-structure",
  },
  {
    slug: "strong-low-weak-high",
    term: "Strong low and weak high",
    aliases: ["strong high", "weak low", "protected low", "strong low", "weak high"],
    category: "structure",
    level: "advanced",
    short: "In an uptrend, the low that launched a break of structure is strong (protected); the newest unbroken high is weak (a likely target).",
    detail: [],
    related: ["internal-structure", "break-of-structure", "draw-on-liquidity"],
    lessonId: "u4-internal-vs-swing-structure",
  },
  {
    slug: "multi-timeframe-analysis",
    term: "Multi-timeframe analysis",
    aliases: ["MTF", "top-down analysis"],
    category: "structure",
    level: "intermediate",
    short: "Using a higher timeframe for direction and a lower one for timing the entry.",
    detail: ["A classic setup: a higher-timeframe uptrend, a lower-timeframe pullback, then a lower-timeframe change of character back up."],
    related: ["timeframe", "bias", "change-of-character"],
    lessonId: "u10-top-down-analysis",
  },
  {
    slug: "dow-theory",
    term: "Dow theory",
    aliases: ["Charles Dow", "William Peter Hamilton", "primary trend", "secondary reaction"],
    category: "structure",
    level: "intermediate",
    short: "Charles Dow's ideas, developed by Hamilton in 1922: trends defined by highs and lows, three trends at once, and confirmation.",
    detail: ["Its accumulation, public participation and distribution phases are the ancestors of Wyckoff and ICT's Power of 3."],
    related: ["higher-high-higher-low", "wyckoff", "power-of-3"],
    lessonId: "u4-where-it-came-from-dow-theory",
  },
]
