import type { GlossaryTerm } from "@/lib/glossary/types"

export const TIME: GlossaryTerm[] = [
  {
    slug: "trading-session",
    term: "Trading session",
    aliases: ["Sydney", "Tokyo", "London", "New York", "session overlap", "Asian session", "London session", "New York session"],
    category: "time",
    level: "beginner",
    short: "The hours when a major financial centre is active; forex moves from Sydney to Tokyo to London to New York.",
    detail: ["The London and New York overlap, about 8 am to 12 pm New York time, is usually the busiest window."],
    related: ["killzone", "asian-range", "pre-market"],
    lessonId: "u1-market-sessions-and-hours",
  },
  {
    slug: "killzone",
    term: "Killzone",
    aliases: ["kill zone", "London open", "New York open", "London close"],
    category: "time",
    level: "intermediate",
    short: "ICT's windows when big moves are most likely: London 2-5 am and New York 7-10 am, New York time.",
    detail: ["Also commonly taught: Asian 8-10 pm and London close 10 am-12 pm. Teachers shift them by up to an hour."],
    visual: "killzone",
    related: ["trading-session", "silver-bullet", "asian-range"],
    lessonId: "u9-sessions-and-killzones",
  },
  {
    slug: "asian-range",
    term: "Asian range",
    category: "time",
    level: "intermediate",
    short: "The high and low of the quiet Asian session; London often sweeps one side of it before the real move.",
    detail: [],
    visual: "asian-range",
    related: ["killzone", "judas-swing", "liquidity-sweep"],
    lessonId: "u9-the-asian-range",
  },
  {
    slug: "midnight-open",
    term: "Midnight open",
    aliases: ["true day open"],
    category: "time",
    level: "advanced",
    short: "The price at 12:00 am New York time, which ICT treats as the start of the trading day.",
    detail: ["On a bullish day, buying below the midnight open is buying at a discount for the day."],
    related: ["power-of-3", "ndog-nwog", "premium-discount"],
    lessonId: "u9-opening-prices-and-opening-gaps",
  },
  {
    slug: "ndog-nwog",
    term: "NDOG and NWOG",
    aliases: ["new day opening gap", "new week opening gap", "opening gap"],
    category: "time",
    level: "advanced",
    short: "Futures gaps between the 5 pm close and the 6 pm reopen (NDOG), or between Friday's close and Sunday's open (NWOG).",
    detail: [],
    related: ["midnight-open", "gap"],
    lessonId: "u9-opening-prices-and-opening-gaps",
  },
  {
    slug: "pre-market",
    term: "Pre-market and after-hours",
    aliases: ["extended hours", "after hours"],
    category: "time",
    level: "beginner",
    short: "Thinner stock trading sessions before 9:30 am and after 4:00 pm New York time, with wider spreads.",
    detail: [],
    related: ["stock", "gap", "spread"],
    lessonId: "u1-market-sessions-and-hours",
  },
]
